package limn.icons.tabler;

/**
 * Tabler's <b>E-commerce</b> icons, one constant per name.
 *
 * <p>Generated. The set is split across one enum per upstream category because a single
 * enum cannot hold it: a class initialiser is capped at 64KB of bytecode and every constant
 * costs roughly twenty of them, so an enum of all 5130
 * names does not compile at all. The categories are upstream's own, and the largest of them
 * is comfortably inside the ceiling.
 */
public enum TablerECommerce implements TablerIcon {

    BACKPACK("backpack"),
    BACKPACK_OFF("backpack-off"),
    BASKET("basket"),
    BASKET_BOLT("basket-bolt"),
    BASKET_CANCEL("basket-cancel"),
    BASKET_CHECK("basket-check"),
    BASKET_CODE("basket-code"),
    BASKET_COG("basket-cog"),
    BASKET_DISCOUNT("basket-discount"),
    BASKET_DOLLAR("basket-dollar"),
    BASKET_DOWN("basket-down"),
    BASKET_EXCLAMATION("basket-exclamation"),
    BASKET_HEART("basket-heart"),
    BASKET_MINUS("basket-minus"),
    BASKET_OFF("basket-off"),
    BASKET_PAUSE("basket-pause"),
    BASKET_PIN("basket-pin"),
    BASKET_PLUS("basket-plus"),
    BASKET_QUESTION("basket-question"),
    BASKET_SEARCH("basket-search"),
    BASKET_SHARE("basket-share"),
    BASKET_STAR("basket-star"),
    BASKET_UP("basket-up"),
    BASKET_X("basket-x"),
    BUSINESSPLAN("businessplan"),
    CASH("cash"),
    CASH_BANKNOTE("cash-banknote"),
    CASH_BANKNOTE_EDIT("cash-banknote-edit"),
    CASH_BANKNOTE_HEART("cash-banknote-heart"),
    CASH_BANKNOTE_MINUS("cash-banknote-minus"),
    CASH_BANKNOTE_MOVE("cash-banknote-move"),
    CASH_BANKNOTE_MOVE_BACK("cash-banknote-move-back"),
    CASH_BANKNOTE_OFF("cash-banknote-off"),
    CASH_BANKNOTE_PLUS("cash-banknote-plus"),
    CASH_EDIT("cash-edit"),
    CASH_HEART("cash-heart"),
    CASH_MINUS("cash-minus"),
    CASH_MOVE("cash-move"),
    CASH_MOVE_BACK("cash-move-back"),
    CASH_OFF("cash-off"),
    CASH_PLUS("cash-plus"),
    CASH_REGISTER("cash-register"),
    CLOTHES_RACK("clothes-rack"),
    CLOTHES_RACK_OFF("clothes-rack-off"),
    COIN("coin"),
    COIN_BITCOIN("coin-bitcoin"),
    COIN_EURO("coin-euro"),
    COIN_MONERO("coin-monero"),
    COIN_OFF("coin-off"),
    COIN_POUND("coin-pound"),
    COIN_RUPEE("coin-rupee"),
    COIN_TAKA("coin-taka"),
    COIN_YEN("coin-yen"),
    COIN_YUAN("coin-yuan"),
    COINS("coins"),
    CREDIT_CARD("credit-card"),
    CREDIT_CARD_HAND("credit-card-hand"),
    CREDIT_CARD_OFF("credit-card-off"),
    CREDIT_CARD_PAY("credit-card-pay"),
    CREDIT_CARD_REFUND("credit-card-refund"),
    DIAPER("diaper"),
    DISCOUNT("discount"),
    DISCOUNT_OFF("discount-off"),
    E_PASSPORT("e-passport"),
    FLIP_FLOPS("flip-flops"),
    GIFT("gift"),
    GIFT_CARD("gift-card"),
    GIFT_OFF("gift-off"),
    HANGER("hanger"),
    HANGER_OFF("hanger-off"),
    JACKET("jacket"),
    MONEYBAG("moneybag"),
    MONEYBAG_EDIT("moneybag-edit"),
    MONEYBAG_HEART("moneybag-heart"),
    MONEYBAG_MINUS("moneybag-minus"),
    MONEYBAG_MOVE("moneybag-move"),
    MONEYBAG_MOVE_BACK("moneybag-move-back"),
    MONEYBAG_PLUS("moneybag-plus"),
    PACKAGE_("package"),
    PACKAGE_OFF("package-off"),
    PERFUME("perfume"),
    RECEIPT_BITCOIN("receipt-bitcoin"),
    RECEIPT_EURO("receipt-euro"),
    RECEIPT_POUND("receipt-pound"),
    RECEIPT_RUPEE("receipt-rupee"),
    RECEIPT_YEN("receipt-yen"),
    RECEIPT_YUAN("receipt-yuan"),
    ROSETTE_DISCOUNT("rosette-discount"),
    ROSETTE_DISCOUNT_CHECK("rosette-discount-check"),
    ROSETTE_DISCOUNT_CHECK_OFF("rosette-discount-check-off"),
    ROSETTE_DISCOUNT_OFF("rosette-discount-off"),
    SHIRT("shirt"),
    SHIRT_OFF("shirt-off"),
    SHIRT_SPORT("shirt-sport"),
    SHOE("shoe"),
    SHOE_OFF("shoe-off"),
    SHOPPING_BAG("shopping-bag"),
    SHOPPING_BAG_CHECK("shopping-bag-check"),
    SHOPPING_BAG_DISCOUNT("shopping-bag-discount"),
    SHOPPING_BAG_EDIT("shopping-bag-edit"),
    SHOPPING_BAG_EXCLAMATION("shopping-bag-exclamation"),
    SHOPPING_BAG_HEART("shopping-bag-heart"),
    SHOPPING_BAG_MINUS("shopping-bag-minus"),
    SHOPPING_BAG_PLUS("shopping-bag-plus"),
    SHOPPING_BAG_SEARCH("shopping-bag-search"),
    SHOPPING_BAG_X("shopping-bag-x"),
    SHOPPING_CART("shopping-cart"),
    SHOPPING_CART_BOLT("shopping-cart-bolt"),
    SHOPPING_CART_CANCEL("shopping-cart-cancel"),
    SHOPPING_CART_CHECK("shopping-cart-check"),
    SHOPPING_CART_CODE("shopping-cart-code"),
    SHOPPING_CART_COG("shopping-cart-cog"),
    SHOPPING_CART_COPY("shopping-cart-copy"),
    SHOPPING_CART_DISCOUNT("shopping-cart-discount"),
    SHOPPING_CART_DOLLAR("shopping-cart-dollar"),
    SHOPPING_CART_DOWN("shopping-cart-down"),
    SHOPPING_CART_EXCLAMATION("shopping-cart-exclamation"),
    SHOPPING_CART_HEART("shopping-cart-heart"),
    SHOPPING_CART_MINUS("shopping-cart-minus"),
    SHOPPING_CART_OFF("shopping-cart-off"),
    SHOPPING_CART_PAUSE("shopping-cart-pause"),
    SHOPPING_CART_PIN("shopping-cart-pin"),
    SHOPPING_CART_PLUS("shopping-cart-plus"),
    SHOPPING_CART_QUESTION("shopping-cart-question"),
    SHOPPING_CART_SEARCH("shopping-cart-search"),
    SHOPPING_CART_SHARE("shopping-cart-share"),
    SHOPPING_CART_STAR("shopping-cart-star"),
    SHOPPING_CART_UP("shopping-cart-up"),
    SHOPPING_CART_X("shopping-cart-x"),
    SOCK("sock"),
    TAG("tag"),
    TAG_MINUS("tag-minus"),
    TAG_OFF("tag-off"),
    TAG_PLUS("tag-plus"),
    TAG_STARRED("tag-starred"),
    TAGS("tags"),
    TAGS_CHEVRON_DOWN("tags-chevron-down"),
    TAGS_CHEVRON_LEFT("tags-chevron-left"),
    TAGS_CHEVRON_RIGHT("tags-chevron-right"),
    TAGS_CHEVRON_UP("tags-chevron-up"),
    TAGS_OFF("tags-off"),
    TIE("tie"),
    TRANSACTION_DOLLAR("transaction-dollar"),
    TRANSACTION_EURO("transaction-euro"),
    TRANSACTION_POUND("transaction-pound"),
    TRANSACTION_YEN("transaction-yen"),
    TRANSACTION_YUAN("transaction-yuan"),
    TRANSFER_IN("transfer-in"),
    TRANSFER_OUT("transfer-out"),
    TRUCK_DELIVERY("truck-delivery"),
    TRUCK_LOADING("truck-loading"),
    TRUCK_RETURN("truck-return"),
    WALLET("wallet"),
    WALLET_OFF("wallet-off");

    private final String iconName;

    TablerECommerce(String iconName) {
        this.iconName = iconName;
    }

    @Override
    public String iconName() {
        return iconName;
    }
}
