package limn.icons.tabler;

/**
 * Tabler's <b>Media</b> icons, one constant per name.
 *
 * <p>Generated. The set is split across one enum per upstream category because a single
 * enum cannot hold it: a class initialiser is capped at 64KB of bytecode and every constant
 * costs roughly twenty of them, so an enum of all 5130
 * names does not compile at all. The categories are upstream's own, and the largest of them
 * is comfortably inside the ceiling.
 */
public enum TablerMedia implements TablerIcon {

    ALBUM("album"),
    ALBUM_OFF("album-off"),
    ASPECT_RATIO("aspect-ratio"),
    ASPECT_RATIO_OFF("aspect-ratio-off"),
    CAMERA("camera"),
    CAMERA_AI("camera-ai"),
    CAMERA_BITCOIN("camera-bitcoin"),
    CAMERA_BOLT("camera-bolt"),
    CAMERA_CANCEL("camera-cancel"),
    CAMERA_CHECK("camera-check"),
    CAMERA_CODE("camera-code"),
    CAMERA_COG("camera-cog"),
    CAMERA_DOLLAR("camera-dollar"),
    CAMERA_DOWN("camera-down"),
    CAMERA_EXCLAMATION("camera-exclamation"),
    CAMERA_HEART("camera-heart"),
    CAMERA_MINUS("camera-minus"),
    CAMERA_MOON("camera-moon"),
    CAMERA_OFF("camera-off"),
    CAMERA_PAUSE("camera-pause"),
    CAMERA_PIN("camera-pin"),
    CAMERA_PLUS("camera-plus"),
    CAMERA_QUESTION("camera-question"),
    CAMERA_SEARCH("camera-search"),
    CAMERA_SHARE("camera-share"),
    CAMERA_SPARK("camera-spark"),
    CAMERA_STAR("camera-star"),
    CAMERA_UP("camera-up"),
    CAMERA_X("camera-x"),
    CAPTURE("capture"),
    CAPTURE_OFF("capture-off"),
    CAST("cast"),
    CAST_OFF("cast-off"),
    CLEF("clef"),
    CLEF_STAFF("clef-staff"),
    HEADPHONES("headphones"),
    HEADPHONES_OFF("headphones-off"),
    HEADSET("headset"),
    HEADSET_OFF("headset-off"),
    KEYFRAME("keyframe"),
    KEYFRAME_ALIGN_CENTER("keyframe-align-center"),
    KEYFRAME_ALIGN_HORIZONTAL("keyframe-align-horizontal"),
    KEYFRAME_ALIGN_VERTICAL("keyframe-align-vertical"),
    KEYFRAMES("keyframes"),
    MAXIMIZE("maximize"),
    MAXIMIZE_OFF("maximize-off"),
    MICROPHONE("microphone"),
    MICROPHONE_2("microphone-2"),
    MICROPHONE_2_OFF("microphone-2-off"),
    MICROPHONE_OFF("microphone-off"),
    MINIMIZE("minimize"),
    MOVIE("movie"),
    MOVIE_OFF("movie-off"),
    MUSIC("music"),
    MUSIC_BOLT("music-bolt"),
    MUSIC_CANCEL("music-cancel"),
    MUSIC_CHECK("music-check"),
    MUSIC_CODE("music-code"),
    MUSIC_COG("music-cog"),
    MUSIC_DOLLAR("music-dollar"),
    MUSIC_DOWN("music-down"),
    MUSIC_EXCLAMATION("music-exclamation"),
    MUSIC_HEART("music-heart"),
    MUSIC_MINUS("music-minus"),
    MUSIC_OFF("music-off"),
    MUSIC_PAUSE("music-pause"),
    MUSIC_PIN("music-pin"),
    MUSIC_PLUS("music-plus"),
    MUSIC_QUESTION("music-question"),
    MUSIC_SEARCH("music-search"),
    MUSIC_SHARE("music-share"),
    MUSIC_STAR("music-star"),
    MUSIC_UP("music-up"),
    MUSIC_X("music-x"),
    PHOTO("photo"),
    PHOTO_AI("photo-ai"),
    PHOTO_ALT("photo-alt"),
    PHOTO_BOLT("photo-bolt"),
    PHOTO_CANCEL("photo-cancel"),
    PHOTO_CHECK("photo-check"),
    PHOTO_CIRCLE_MINUS("photo-circle-minus"),
    PHOTO_CIRCLE_PLUS("photo-circle-plus"),
    PHOTO_CODE("photo-code"),
    PHOTO_COG("photo-cog"),
    PHOTO_DOLLAR("photo-dollar"),
    PHOTO_DOWN("photo-down"),
    PHOTO_EDIT("photo-edit"),
    PHOTO_EXCLAMATION("photo-exclamation"),
    PHOTO_HEART("photo-heart"),
    PHOTO_MINUS("photo-minus"),
    PHOTO_OFF("photo-off"),
    PHOTO_PAUSE("photo-pause"),
    PHOTO_PIN("photo-pin"),
    PHOTO_PLUS("photo-plus"),
    PHOTO_QUESTION("photo-question"),
    PHOTO_SEARCH("photo-search"),
    PHOTO_SHARE("photo-share"),
    PHOTO_SHIELD("photo-shield"),
    PHOTO_SPARK("photo-spark"),
    PHOTO_STAR("photo-star"),
    PHOTO_UP("photo-up"),
    PHOTO_X("photo-x"),
    PICTURE_IN_PICTURE("picture-in-picture"),
    PICTURE_IN_PICTURE_OFF("picture-in-picture-off"),
    PICTURE_IN_PICTURE_ON("picture-in-picture-on"),
    PICTURE_IN_PICTURE_TOP("picture-in-picture-top"),
    PLAYER_EJECT("player-eject"),
    PLAYER_PAUSE("player-pause"),
    PLAYER_PLAY("player-play"),
    PLAYER_RECORD("player-record"),
    PLAYER_SKIP_BACK("player-skip-back"),
    PLAYER_SKIP_FORWARD("player-skip-forward"),
    PLAYER_STOP("player-stop"),
    PLAYER_TRACK_NEXT("player-track-next"),
    PLAYER_TRACK_PREV("player-track-prev"),
    PLAYLIST("playlist"),
    PLAYLIST_OFF("playlist-off"),
    PLAYLIST_X("playlist-x"),
    RADIO("radio"),
    RADIO_OFF("radio-off"),
    REPEAT("repeat"),
    REPEAT_OFF("repeat-off"),
    REPEAT_ONCE("repeat-once"),
    REWIND_BACKWARD_10("rewind-backward-10"),
    REWIND_BACKWARD_15("rewind-backward-15"),
    REWIND_BACKWARD_20("rewind-backward-20"),
    REWIND_BACKWARD_30("rewind-backward-30"),
    REWIND_BACKWARD_40("rewind-backward-40"),
    REWIND_BACKWARD_5("rewind-backward-5"),
    REWIND_BACKWARD_50("rewind-backward-50"),
    REWIND_BACKWARD_60("rewind-backward-60"),
    REWIND_FORWARD_10("rewind-forward-10"),
    REWIND_FORWARD_15("rewind-forward-15"),
    REWIND_FORWARD_20("rewind-forward-20"),
    REWIND_FORWARD_30("rewind-forward-30"),
    REWIND_FORWARD_40("rewind-forward-40"),
    REWIND_FORWARD_5("rewind-forward-5"),
    REWIND_FORWARD_50("rewind-forward-50"),
    REWIND_FORWARD_60("rewind-forward-60"),
    SHAREPLAY("shareplay"),
    SPEAKERPHONE("speakerphone"),
    SUBTITLES("subtitles"),
    SUBTITLES_AI("subtitles-ai"),
    SUBTITLES_EDIT("subtitles-edit"),
    SUBTITLES_OFF("subtitles-off"),
    USER_SCREEN("user-screen"),
    VIDEO("video"),
    VIDEO_MINUS("video-minus"),
    VIDEO_OFF("video-off"),
    VIDEO_PLUS("video-plus"),
    VOLUME("volume"),
    VOLUME_2("volume-2"),
    VOLUME_3("volume-3"),
    VOLUME_4("volume-4"),
    VOLUME_OFF("volume-off");

    private final String iconName;

    TablerMedia(String iconName) {
        this.iconName = iconName;
    }

    @Override
    public String iconName() {
        return iconName;
    }
}
