package limn.icons.tabler;

/**
 * Tabler's <b>Communication</b> icons, one constant per name.
 *
 * <p>Generated. The set is split across one enum per upstream category because a single
 * enum cannot hold it: a class initialiser is capped at 64KB of bytecode and every constant
 * costs roughly twenty of them, so an enum of all 5130
 * names does not compile at all. The categories are upstream's own, and the largest of them
 * is comfortably inside the ceiling.
 */
public enum TablerCommunication implements TablerIcon {

    ADDRESS_BOOK("address-book"),
    ADDRESS_BOOK_OFF("address-book-off"),
    BUBBLE("bubble"),
    BUBBLE_MINUS("bubble-minus"),
    BUBBLE_PLUS("bubble-plus"),
    BUBBLE_TEXT("bubble-text"),
    BUBBLE_X("bubble-x"),
    EMAIL_STAMP("email-stamp"),
    MAIL("mail"),
    MAIL_AI("mail-ai"),
    MAIL_BITCOIN("mail-bitcoin"),
    MAIL_BOLT("mail-bolt"),
    MAIL_CANCEL("mail-cancel"),
    MAIL_CHECK("mail-check"),
    MAIL_CODE("mail-code"),
    MAIL_COG("mail-cog"),
    MAIL_DOLLAR("mail-dollar"),
    MAIL_DOWN("mail-down"),
    MAIL_EXCLAMATION("mail-exclamation"),
    MAIL_FAST("mail-fast"),
    MAIL_FORWARD("mail-forward"),
    MAIL_HEART("mail-heart"),
    MAIL_MINUS("mail-minus"),
    MAIL_OFF("mail-off"),
    MAIL_OPENED("mail-opened"),
    MAIL_PAUSE("mail-pause"),
    MAIL_PIN("mail-pin"),
    MAIL_PLUS("mail-plus"),
    MAIL_QUESTION("mail-question"),
    MAIL_SEARCH("mail-search"),
    MAIL_SHARE("mail-share"),
    MAIL_SPARK("mail-spark"),
    MAIL_STAR("mail-star"),
    MAIL_UP("mail-up"),
    MAIL_X("mail-x"),
    MAILBOX("mailbox"),
    MAILBOX_OFF("mailbox-off"),
    MESSAGE("message"),
    MESSAGE_2("message-2"),
    MESSAGE_2_BOLT("message-2-bolt"),
    MESSAGE_2_CANCEL("message-2-cancel"),
    MESSAGE_2_CHECK("message-2-check"),
    MESSAGE_2_CODE("message-2-code"),
    MESSAGE_2_COG("message-2-cog"),
    MESSAGE_2_DOLLAR("message-2-dollar"),
    MESSAGE_2_DOWN("message-2-down"),
    MESSAGE_2_EXCLAMATION("message-2-exclamation"),
    MESSAGE_2_HEART("message-2-heart"),
    MESSAGE_2_MINUS("message-2-minus"),
    MESSAGE_2_OFF("message-2-off"),
    MESSAGE_2_PAUSE("message-2-pause"),
    MESSAGE_2_PIN("message-2-pin"),
    MESSAGE_2_PLUS("message-2-plus"),
    MESSAGE_2_QUESTION("message-2-question"),
    MESSAGE_2_SEARCH("message-2-search"),
    MESSAGE_2_SHARE("message-2-share"),
    MESSAGE_2_STAR("message-2-star"),
    MESSAGE_2_UP("message-2-up"),
    MESSAGE_2_X("message-2-x"),
    MESSAGE_BOLT("message-bolt"),
    MESSAGE_CANCEL("message-cancel"),
    MESSAGE_CHATBOT("message-chatbot"),
    MESSAGE_CHECK("message-check"),
    MESSAGE_CIRCLE("message-circle"),
    MESSAGE_CIRCLE_BOLT("message-circle-bolt"),
    MESSAGE_CIRCLE_CANCEL("message-circle-cancel"),
    MESSAGE_CIRCLE_CHECK("message-circle-check"),
    MESSAGE_CIRCLE_CODE("message-circle-code"),
    MESSAGE_CIRCLE_COG("message-circle-cog"),
    MESSAGE_CIRCLE_DOLLAR("message-circle-dollar"),
    MESSAGE_CIRCLE_DOWN("message-circle-down"),
    MESSAGE_CIRCLE_EXCLAMATION("message-circle-exclamation"),
    MESSAGE_CIRCLE_HEART("message-circle-heart"),
    MESSAGE_CIRCLE_MINUS("message-circle-minus"),
    MESSAGE_CIRCLE_OFF("message-circle-off"),
    MESSAGE_CIRCLE_PAUSE("message-circle-pause"),
    MESSAGE_CIRCLE_PIN("message-circle-pin"),
    MESSAGE_CIRCLE_PLUS("message-circle-plus"),
    MESSAGE_CIRCLE_QUESTION("message-circle-question"),
    MESSAGE_CIRCLE_SEARCH("message-circle-search"),
    MESSAGE_CIRCLE_SHARE("message-circle-share"),
    MESSAGE_CIRCLE_STAR("message-circle-star"),
    MESSAGE_CIRCLE_UP("message-circle-up"),
    MESSAGE_CIRCLE_USER("message-circle-user"),
    MESSAGE_CIRCLE_X("message-circle-x"),
    MESSAGE_CODE("message-code"),
    MESSAGE_COG("message-cog"),
    MESSAGE_DOLLAR("message-dollar"),
    MESSAGE_DOTS("message-dots"),
    MESSAGE_DOWN("message-down"),
    MESSAGE_EXCLAMATION("message-exclamation"),
    MESSAGE_FORWARD("message-forward"),
    MESSAGE_HEART("message-heart"),
    MESSAGE_LANGUAGE("message-language"),
    MESSAGE_MINUS("message-minus"),
    MESSAGE_OFF("message-off"),
    MESSAGE_PAUSE("message-pause"),
    MESSAGE_PIN("message-pin"),
    MESSAGE_PLUS("message-plus"),
    MESSAGE_QUESTION("message-question"),
    MESSAGE_REPLY("message-reply"),
    MESSAGE_REPORT("message-report"),
    MESSAGE_SEARCH("message-search"),
    MESSAGE_SHARE("message-share"),
    MESSAGE_STAR("message-star"),
    MESSAGE_UP("message-up"),
    MESSAGE_USER("message-user"),
    MESSAGE_X("message-x"),
    MESSAGES("messages"),
    MESSAGES_OFF("messages-off"),
    PHONE_DONE("phone-done"),
    PHONE_END("phone-end"),
    PHONE_RINGING("phone-ringing"),
    RSS("rss"),
    SEND("send"),
    SEND_2("send-2"),
    SEND_OFF("send-off");

    private final String iconName;

    TablerCommunication(String iconName) {
        this.iconName = iconName;
    }

    @Override
    public String iconName() {
        return iconName;
    }
}
