import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import sitemap from "@astrojs/sitemap";
import { DEFAULT_LOCALE } from "./src/lib/i18n";
import { THEME_COLOR_SCRIPT } from "./src/lib/theme-script.mjs";
import { apiSitemapUrls } from "./scripts/api-sitemap.mjs";

// `site` and `base` come from the environment and from nowhere else. On
// <user>.github.io/limn/ the site lives under /limn/; on a custom domain it does not, and
// a single absolute path hard-coded in a component breaks every asset URL under one of
// those two. Components build URLs with Astro's `base`, never with a leading slash of
// their own.
const SITE = process.env.SITE_URL ?? "http://localhost:4321";
const BASE = process.env.SITE_BASE ?? "/";

// The localhost fallback exists for `astro dev` and local preview only. A CI build that
// forgot SITE_URL would otherwise bake http://localhost:4321 into the sitemap silently;
// canonical/hreflang/og already gate themselves on the env var in Page.astro, but the
// sitemap comes from `site` and cannot.
if (process.env.CI && !process.env.SITE_URL) {
  throw new Error("SITE_URL must be set for a CI build; the sitemap is generated from it.");
}

// `/api/` is a static tree in `public/`, staged there by `scripts/build-api.mjs` and
// never routed by Astro, so the sitemap integration cannot see it: it is enumerated from
// disk and handed over as `customPages` below. Empty means the generators have not run:
// survivable under `astro dev`, a silently `/api/`-less sitemap on a deploy, so the CI
// case refuses the same way the SITE_URL guard above does.
const API_PAGES = apiSitemapUrls(SITE, BASE);
if (process.env.CI && API_PAGES.length === 0) {
  throw new Error(
    "No /api/ pages found for the sitemap. Run the generators (pnpm generate) before astro build.",
  );
}

export default defineConfig({
  output: "static",
  site: SITE,
  base: BASE,
  trailingSlash: "always",
  // Astro's own `i18n` block is deliberately absent. Turning it on makes Starlight read the
  // first path segment as a locale, and the guide, which is English-only, came out
  // duplicated at every prefix, plus a second copy of the whole set outside /docs/. So
  // locale routing for the marketing pages is driven from src/lib/i18n.ts instead, and
  // Starlight keeps a single root locale. The two no longer share a mechanism, which is why
  // they no longer fight.
  integrations: [
    starlight({
      title: "Limn",
      // The delivered lockup, so the guide's header is the same mark as the marketing
      // pages'. Starlight swaps the two files on its own theme switch, which is why both
      // variants are named here rather than one file carrying a media query.
      logo: {
        light: "./src/brand/limn-lockup-light.svg",
        dark: "./src/brand/limn-lockup-dark.svg",
        replacesTitle: true,
      },
      defaultLocale: "root",
      locales: { root: { label: "English", lang: DEFAULT_LOCALE } },
      customCss: ["./src/styles/starlight.css"],
      // The guide runs Starlight's own layout, not this site's, so the browser-chrome tint has to
      // be injected here as well, using the same one definition, not a second copy. Starlight already
      // stamps `data-theme` from the same storage key, which is what the script watches.
      head: [{ tag: "script", content: THEME_COLOR_SCRIPT }],
      // The guide keeps Starlight's frame (sidebar, table of contents, search) and gets
      // the site's own bar in place of the default one, so that /docs/ is the same product
      // as the page it was linked from rather than a documentation theme beside it. The
      // mobile footer is overridden with it: replacing the header moves the navigation and
      // the theme control off a phone unless they land somewhere else.
      components: {
        Header: "./src/components/starlight/Header.astro",
        MobileMenuFooter: "./src/components/starlight/MobileMenuFooter.astro",
      },
      // The site has its own 404, which is the one a reader should get anywhere on the
      // domain. Two static routes for /404 is a warning today and a hard error in a later
      // Astro, so Starlight's is turned off rather than shadowed.
      disable404Route: true,
      // Pagefind, which Starlight enables by default: static, no service, works on Pages.
      pagefind: true,
      // The order a reader meets the toolkit in, not the order the files sit in. It is
      // written out rather than autogenerated for exactly that reason.
      sidebar: [
        {
          label: "Start here",
          items: [
            { slug: "docs" },
            { slug: "docs/install" },
            { slug: "docs/widgets" },
          ],
        },
        {
          label: "Building a screen",
          items: [
            { slug: "docs/layout" },
            { slug: "docs/forms" },
            { slug: "docs/lists-and-scrolling" },
            { slug: "docs/menus-and-dialogs" },
            { slug: "docs/charts" },
          ],
        },
        {
          label: "Making it yours",
          items: [
            { slug: "docs/theming" },
            { slug: "docs/text-and-languages" },
            { slug: "docs/images-and-media" },
          ],
        },
        {
          label: "Shipping",
          items: [
            { slug: "docs/background-work" },
            { slug: "docs/packaging" },
          ],
        },
      ],
    }),
    // Declared explicitly so it can be configured. Left out, Starlight injects its own
    // copy with no filter and no way to reach the static `/api/` tree. Starlight sees
    // this declaration and stands down, so removing it does not remove the sitemap; it
    // removes the filter and `/api/`, and F5 comes back.
    sitemap({
      // `/get-started/` is a deliberate `noindex` moved-page stub; a sitemap listing it
      // is the "Submitted URL marked 'noindex'" contradiction. The integration excludes
      // the other `noindex` page (the 404) on its own.
      filter: (page) => !page.endsWith("/get-started/"),
      customPages: API_PAGES,
    }),
  ],
});
