package limn.demo.site;

import limn.components.SizeTokens;
import limn.components.Theme;
import limn.scene.ControlSize;
import limn.graphics.Color;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes the {@code Limn} and {@code Limn Light} palettes out as CSS custom properties,
 * for the public site to consume.
 *
 * <p>The site is dark violet because the toolkit is, and a hex value copied from
 * {@link Theme} into a stylesheet is a fact that either file can change without the other
 * noticing; the screenshots would drift away from the page around them one tone at a
 * time, which is exactly the failure the gallery exists to prevent. So the stylesheet is
 * generated from the palettes themselves and never hand-written.
 *
 * <p>Emits four blocks, in this order and for this reason: {@code :root} carries the light
 * palette, a {@code prefers-color-scheme: dark} query supplies the dark one as the system
 * default, and two {@code :root[data-theme=…]} blocks follow so that an explicit choice
 * wins over the system in <em>both</em> directions. A reader who forces light on a machine
 * set to dark is the case that breaks when those last two blocks are omitted.
 *
 * <p>Run as {@code java limn.demo.site.ThemeTokens <output.css>}; no window, no GL context
 * and no UI thread: it reads static palette data and writes a file.
 */
public final class ThemeTokens {

    private ThemeTokens() {
    }

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            System.err.println("usage: ThemeTokens <output.css>");
            System.exit(2);
        }
        Path out = Path.of(args[0]);
        Path parent = out.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(out, render(), StandardCharsets.UTF_8);
        System.out.println("theme tokens written to " + out.toAbsolutePath());
    }

    static String render() {
        Theme dark = Theme.limn();
        Theme light = Theme.limnLight();
        StringBuilder css = new StringBuilder();
        css.append("""
                /* GENERATED by limn.demo.site.ThemeTokens. Do not edit.
                 * Source of truth: limn.components.Theme.limn() and Theme.limnLight().
                 * Regenerate with: ./gradlew :limn-demo:exportThemeTokens
                 */
                """);
        css.append(":root {\n").append(palette(light)).append(metrics()).append("}\n\n");
        css.append("@media (prefers-color-scheme: dark) {\n  :root {\n")
                .append(indent(palette(dark))).append("  }\n}\n\n");
        css.append(":root[data-theme=\"light\"] {\n").append(palette(light)).append("}\n\n");
        css.append(":root[data-theme=\"dark\"] {\n").append(palette(dark)).append("}\n");
        return css.toString();
    }

    private static String palette(Theme t) {
        StringBuilder b = new StringBuilder();
        b.append("  --limn-color-scheme: ").append(t.dark ? "dark" : "light").append(";\n");
        token(b, "background", t.background);
        token(b, "surface", t.surface);
        token(b, "surface-raised", t.surfaceRaised);
        token(b, "primary", t.primary);
        token(b, "primary-hover", t.primaryHover);
        token(b, "primary-pressed", t.primaryPressed);
        token(b, "on-primary", t.onPrimary);
        token(b, "text", t.text);
        token(b, "text-muted", t.textMuted);
        token(b, "outline", t.outline);
        token(b, "focus-ring", t.focusRing);
        token(b, "disabled-fill", t.disabledFill);
        token(b, "disabled-text", t.disabledText);
        token(b, "danger", t.danger);
        token(b, "success", t.success);
        token(b, "warning", t.warning);
        token(b, "info", t.info);
        return b.toString();
    }

    /**
     * Radii and spacing, emitted once rather than per palette. Spacing is palette-independent
     * by construction; the radii are read off the palette's own MEDIUM row, so a site built
     * from a palette with a shape of its own gets that shape rather than the default ramp.
     */
    private static String metrics() {
        Theme t = Theme.limn();
        SizeTokens medium = t.tokens(ControlSize.MEDIUM);
        return "  --limn-radius-small: " + px(medium.radiusSmall()) + ";\n"
                + "  --limn-radius-medium: " + px(medium.radiusMedium()) + ";\n"
                + "  --limn-radius-large: " + px(medium.radiusLarge()) + ";\n"
                + "  --limn-space-small: " + px(t.spacingSmall) + ";\n"
                + "  --limn-space-medium: " + px(t.spacingMedium) + ";\n"
                + "  --limn-space-large: " + px(t.spacingLarge) + ";\n";
    }

    private static void token(StringBuilder b, String name, Color c) {
        b.append("  --limn-").append(name).append(": ").append(hex(c)).append(";\n");
    }

    /**
     * {@code #rrggbb}, or {@code #rrggbbaa} when the tone is not opaque. Every palette tone
     * is opaque today; the alpha branch is here so that a translucent one added later is
     * exported rather than silently flattened to its RGB.
     */
    static String hex(Color c) {
        String rgb = String.format("#%02X%02X%02X", channel(c.r()), channel(c.g()), channel(c.b()));
        return c.a() >= 1f ? rgb : rgb + String.format("%02X", channel(c.a()));
    }

    private static int channel(float value) {
        return Math.round(Math.max(0f, Math.min(1f, value)) * 255f);
    }

    private static String px(float value) {
        return value == Math.rint(value) ? (int) value + "px" : value + "px";
    }

    private static String indent(String block) {
        return block.replaceAll("(?m)^(?=.)", "  ");
    }
}
